=== ilwu/RbtProject/srcAllen/com/rbt/export/test/excel-operate-export.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ====================================== -->
<!-- ELEMENT : config-->
<!-- ====================================== -->
<!ELEMENT config (excel+|function*)*>

<!-- ====================================== -->
<!-- ELEMENT : function -->
<!-- ====================================== -->
<!ELEMENT function EMPTY>
<!ATTLIST function
	funcId ID #REQUIRED
	className CDATA #REQUIRED
	method CDATA #REQUIRED
>

<!-- ====================================== -->
<!-- ELEMENT : excel-->
<!-- ====================================== -->
<!ELEMENT excel (style?|sheet+)+>
<!ATTLIST excel
	id CDATA #REQUIRED
	fileName CDATA #REQUIRED
	paperSize (A2|A3|A4|A5|B4|B5) "A4"
>

<!-- ====================================== -->
<!-- ELEMENT : style-->
<!-- ====================================== -->
<!ELEMENT style EMPTY>
<!ATTLIST style
	font CDATA #IMPLIED
	size CDATA #IMPLIED
	bold (true|false) #IMPLIED
	italic (true|false) #IMPLIED
	underline (true|false) #IMPLIED
	color (AQUA|AUTOMATIC|BLACK|BLUE_GREY|BLUE|BLUE2|BRIGHT_GREEN|BROWN|CORAL|DARK_BLUE|DARK_BLUE2|DARK_GREEN|DARK_PURPLE|DARK_RED|DARK_RED2|DARK_TEAL|DARK_YELLOW|GOLD|GRAY_25|GRAY_50|GRAY_80|GREEN|GREY_25_PERCENT|GREY_40_PERCENT|GREY_50_PERCENT|GREY_80_PERCENT|ICE_BLUE|INDIGO|IVORY|LAVENDER|LIGHT_BLUE|LIGHT_GREEN|LIGHT_ORANGE|LIGHT_TURQUOISE|LIGHT_TURQUOISE2|LIME|OCEAN_BLUE|OLIVE_GREEN|ORANGE|PALE_BLUE|PERIWINKLE|PINK|PINK2|PLUM|PLUM2|RED|ROSE|SEA_GREEN|SKY_BLUE|TAN|TEAL|TEAL2|TURQOISE2|TURQUOISE|VERY_LIGHT_YELLOW|VIOLET|VIOLET2|WHITE|YELLOW|YELLOW2) #IMPLIED
	align (center|left|right) #IMPLIED
	valign (center|top|bottom) #IMPLIED
	width CDATA #IMPLIED
	wrap (true|false) #IMPLIED
	background (AQUA|AUTOMATIC|BLACK|BLUE_GREY|BLUE|BLUE2|BRIGHT_GREEN|BROWN|CORAL|DARK_BLUE|DARK_BLUE2|DARK_GREEN|DARK_PURPLE|DARK_RED|DARK_RED2|DARK_TEAL|DARK_YELLOW|GOLD|GRAY_25|GRAY_50|GRAY_80|GREEN|GREY_25_PERCENT|GREY_40_PERCENT|GREY_50_PERCENT|GREY_80_PERCENT|ICE_BLUE|INDIGO|IVORY|LAVENDER|LIGHT_BLUE|LIGHT_GREEN|LIGHT_ORANGE|LIGHT_TURQUOISE|LIGHT_TURQUOISE2|LIME|OCEAN_BLUE|OLIVE_GREEN|ORANGE|PALE_BLUE|PERIWINKLE|PINK|PINK2|PLUM|PLUM2|RED|ROSE|SEA_GREEN|SKY_BLUE|TAN|TEAL|TEAL2|TURQOISE2|TURQUOISE|VERY_LIGHT_YELLOW|VIOLET|VIOLET2|WHITE|YELLOW|YELLOW2) #IMPLIED
	borderSide (NONE|ALL|TOP|BOTTOM|LEFT|RIGHT) #IMPLIED
	borderStyle (NONE|THIN|MEDIUM|DASHED|DOTTED|THICK|DOUBLE|HAIR|MEDIUM_DASHED|DASH_DOT|MEDIUM_DASH_DOT|DASH_DOT_DOT|MEDIUM_DASH_DOT_DOT|SLANTED_DASH_DOT) #IMPLIED
>

<!-- ====================================== -->
<!-- ELEMENT : sheet-->
<!-- ====================================== -->
<!ELEMENT sheet (context*|detail*)+ >
<!ATTLIST sheet
	sheetName CDATA #IMPLIED
>

<!-- ====================================== -->
<!-- ELEMENT : context (固定欄位, 不跑迴圈) -->
<!-- ====================================== -->
<!ELEMENT context (tr+)>
<!ATTLIST context
	dataId CDATA #REQUIRED
>

<!-- ====================================== -->
<!-- ELEMENT : tr-->
<!-- ====================================== -->
<!ELEMENT tr (td+)>
<!ATTLIST tr
	font CDATA #IMPLIED
	size CDATA #IMPLIED
	bold (true|false) #IMPLIED
	italic (true|false) #IMPLIED
	underline (true|false) #IMPLIED
	color (AQUA|AUTOMATIC|BLACK|BLUE_GREY|BLUE|BLUE2|BRIGHT_GREEN|BROWN|CORAL|DARK_BLUE|DARK_BLUE2|DARK_GREEN|DARK_PURPLE|DARK_RED|DARK_RED2|DARK_TEAL|DARK_YELLOW|GOLD|GRAY_25|GRAY_50|GRAY_80|GREEN|GREY_25_PERCENT|GREY_40_PERCENT|GREY_50_PERCENT|GREY_80_PERCENT|ICE_BLUE|INDIGO|IVORY|LAVENDER|LIGHT_BLUE|LIGHT_GREEN|LIGHT_ORANGE|LIGHT_TURQUOISE|LIGHT_TURQUOISE2|LIME|OCEAN_BLUE|OLIVE_GREEN|ORANGE|PALE_BLUE|PERIWINKLE|PINK|PINK2|PLUM|PLUM2|RED|ROSE|SEA_GREEN|SKY_BLUE|TAN|TEAL|TEAL2|TURQOISE2|TURQUOISE|VERY_LIGHT_YELLOW|VIOLET|VIOLET2|WHITE|YELLOW|YELLOW2) #IMPLIED
	align (center|left|right) #IMPLIED
	valign (center|top|bottom) #IMPLIED
	width CDATA #IMPLIED
	wrap (true|false) #IMPLIED
	background (AQUA|AUTOMATIC|BLACK|BLUE_GREY|BLUE|BLUE2|BRIGHT_GREEN|BROWN|CORAL|DARK_BLUE|DARK_BLUE2|DARK_GREEN|DARK_PURPLE|DARK_RED|DARK_RED2|DARK_TEAL|DARK_YELLOW|GOLD|GRAY_25|GRAY_50|GRAY_80|GREEN|GREY_25_PERCENT|GREY_40_PERCENT|GREY_50_PERCENT|GREY_80_PERCENT|ICE_BLUE|INDIGO|IVORY|LAVENDER|LIGHT_BLUE|LIGHT_GREEN|LIGHT_ORANGE|LIGHT_TURQUOISE|LIGHT_TURQUOISE2|LIME|OCEAN_BLUE|OLIVE_GREEN|ORANGE|PALE_BLUE|PERIWINKLE|PINK|PINK2|PLUM|PLUM2|RED|ROSE|SEA_GREEN|SKY_BLUE|TAN|TEAL|TEAL2|TURQOISE2|TURQUOISE|VERY_LIGHT_YELLOW|VIOLET|VIOLET2|WHITE|YELLOW|YELLOW2) #IMPLIED
	borderSide (NONE|ALL|TOP|BOTTOM|LEFT|RIGHT) #IMPLIED
	borderStyle (NONE|THIN|MEDIUM|DASHED|DOTTED|THICK|DOUBLE|HAIR|MEDIUM_DASHED|DASH_DOT|MEDIUM_DASH_DOT|DASH_DOT_DOT|MEDIUM_DASH_DOT_DOT|SLANTED_DASH_DOT) #IMPLIED
>

<!-- ====================================== -->
<!-- ELEMENT : td -->
<!-- ====================================== -->
<!ELEMENT td (defaultValue?)>
<!ATTLIST td
	key CDATA #IMPLIED
	defaultValue CDATA #IMPLIED
	funcId CDATA #IMPLIED
	funcParam CDATA #IMPLIED
	rowspan CDATA #IMPLIED
	colspan CDATA #IMPLIED

	font CDATA #IMPLIED
	size CDATA #IMPLIED
	bold (true|false) #IMPLIED
	italic (true|false) #IMPLIED
	underline (true|false) #IMPLIED
	color (AQUA|AUTOMATIC|BLACK|BLUE_GREY|BLUE|BLUE2|BRIGHT_GREEN|BROWN|CORAL|DARK_BLUE|DARK_BLUE2|DARK_GREEN|DARK_PURPLE|DARK_RED|DARK_RED2|DARK_TEAL|DARK_YELLOW|GOLD|GRAY_25|GRAY_50|GRAY_80|GREEN|GREY_25_PERCENT|GREY_40_PERCENT|GREY_50_PERCENT|GREY_80_PERCENT|ICE_BLUE|INDIGO|IVORY|LAVENDER|LIGHT_BLUE|LIGHT_GREEN|LIGHT_ORANGE|LIGHT_TURQUOISE|LIGHT_TURQUOISE2|LIME|OCEAN_BLUE|OLIVE_GREEN|ORANGE|PALE_BLUE|PERIWINKLE|PINK|PINK2|PLUM|PLUM2|RED|ROSE|SEA_GREEN|SKY_BLUE|TAN|TEAL|TEAL2|TURQOISE2|TURQUOISE|VERY_LIGHT_YELLOW|VIOLET|VIOLET2|WHITE|YELLOW|YELLOW2) #IMPLIED
	align (center|left|right) #IMPLIED
	valign (center|top|bottom) #IMPLIED
	width CDATA #IMPLIED
	wrap (true|false) #IMPLIED
	background (AQUA|AUTOMATIC|BLACK|BLUE_GREY|BLUE|BLUE2|BRIGHT_GREEN|BROWN|CORAL|DARK_BLUE|DARK_BLUE2|DARK_GREEN|DARK_PURPLE|DARK_RED|DARK_RED2|DARK_TEAL|DARK_YELLOW|GOLD|GRAY_25|GRAY_50|GRAY_80|GREEN|GREY_25_PERCENT|GREY_40_PERCENT|GREY_50_PERCENT|GREY_80_PERCENT|ICE_BLUE|INDIGO|IVORY|LAVENDER|LIGHT_BLUE|LIGHT_GREEN|LIGHT_ORANGE|LIGHT_TURQUOISE|LIGHT_TURQUOISE2|LIME|OCEAN_BLUE|OLIVE_GREEN|ORANGE|PALE_BLUE|PERIWINKLE|PINK|PINK2|PLUM|PLUM2|RED|ROSE|SEA_GREEN|SKY_BLUE|TAN|TEAL|TEAL2|TURQOISE2|TURQUOISE|VERY_LIGHT_YELLOW|VIOLET|VIOLET2|WHITE|YELLOW|YELLOW2) #IMPLIED
	borderSide (NONE|ALL|TOP|BOTTOM|LEFT|RIGHT) #IMPLIED
	borderStyle (NONE|THIN|MEDIUM|DASHED|DOTTED|THICK|DOUBLE|HAIR|MEDIUM_DASHED|DASH_DOT|MEDIUM_DASH_DOT|DASH_DOT_DOT|MEDIUM_DASH_DOT_DOT|SLANTED_DASH_DOT) #IMPLIED
>

<!-- ====================================== -->
<!-- ELEMENT : detail (迴圈欄位) -->
<!-- ====================================== -->
<!ELEMENT detail (column+)>
<!ATTLIST detail
	dataId CDATA #REQUIRED
>
<!-- ====================================== -->
<!-- ELEMENT : column  -->
<!-- ====================================== -->
<!ELEMENT column (array*|single*|defaultValue?)*>
<!ATTLIST column
	key  CDATA #IMPLIED
	defaultValue CDATA #IMPLIED
	funcId CDATA #IMPLIED
	funcParam CDATA #IMPLIED
	colspan CDATA #IMPLIED
	width CDATA #IMPLIED

	font CDATA #IMPLIED
	size CDATA #IMPLIED
	bold (true|false) #IMPLIED
	italic (true|false) #IMPLIED
	underline (true|false) #IMPLIED
	color (AQUA|AUTOMATIC|BLACK|BLUE_GREY|BLUE|BLUE2|BRIGHT_GREEN|BROWN|CORAL|DARK_BLUE|DARK_BLUE2|DARK_GREEN|DARK_PURPLE|DARK_RED|DARK_RED2|DARK_TEAL|DARK_YELLOW|GOLD|GRAY_25|GRAY_50|GRAY_80|GREEN|GREY_25_PERCENT|GREY_40_PERCENT|GREY_50_PERCENT|GREY_80_PERCENT|ICE_BLUE|INDIGO|IVORY|LAVENDER|LIGHT_BLUE|LIGHT_GREEN|LIGHT_ORANGE|LIGHT_TURQUOISE|LIGHT_TURQUOISE2|LIME|OCEAN_BLUE|OLIVE_GREEN|ORANGE|PALE_BLUE|PERIWINKLE|PINK|PINK2|PLUM|PLUM2|RED|ROSE|SEA_GREEN|SKY_BLUE|TAN|TEAL|TEAL2|TURQOISE2|TURQUOISE|VERY_LIGHT_YELLOW|VIOLET|VIOLET2|WHITE|YELLOW|YELLOW2) #IMPLIED
	align (center|left|right) #IMPLIED
	valign (center|top|bottom) #IMPLIED
	wrap (true|false) #IMPLIED
	background (AQUA|AUTOMATIC|BLACK|BLUE_GREY|BLUE|BLUE2|BRIGHT_GREEN|BROWN|CORAL|DARK_BLUE|DARK_BLUE2|DARK_GREEN|DARK_PURPLE|DARK_RED|DARK_RED2|DARK_TEAL|DARK_YELLOW|GOLD|GRAY_25|GRAY_50|GRAY_80|GREEN|GREY_25_PERCENT|GREY_40_PERCENT|GREY_50_PERCENT|GREY_80_PERCENT|ICE_BLUE|INDIGO|IVORY|LAVENDER|LIGHT_BLUE|LIGHT_GREEN|LIGHT_ORANGE|LIGHT_TURQUOISE|LIGHT_TURQUOISE2|LIME|OCEAN_BLUE|OLIVE_GREEN|ORANGE|PALE_BLUE|PERIWINKLE|PINK|PINK2|PLUM|PLUM2|RED|ROSE|SEA_GREEN|SKY_BLUE|TAN|TEAL|TEAL2|TURQOISE2|TURQUOISE|VERY_LIGHT_YELLOW|VIOLET|VIOLET2|WHITE|YELLOW|YELLOW2) #IMPLIED
	borderSide (NONE|ALL|TOP|BOTTOM|LEFT|RIGHT) #IMPLIED
	borderStyle (NONE|THIN|MEDIUM|DASHED|DOTTED|THICK|DOUBLE|HAIR|MEDIUM_DASHED|DASH_DOT|MEDIUM_DASH_DOT|DASH_DOT_DOT|MEDIUM_DASH_DOT_DOT|SLANTED_DASH_DOT) #IMPLIED
>

<!-- ====================================== -->
<!-- ELEMENT : array 多筆欄位 -->
<!-- ====================================== -->
<!ELEMENT array (column+)>
<!ATTLIST array
	dataId CDATA #REQUIRED
>
<!-- ====================================== -->
<!-- ELEMENT : single 單筆欄位 -->
<!-- ====================================== -->
<!ELEMENT single (column+)>
<!ATTLIST single
	dataId CDATA #REQUIRED
>


<!-- ====================================== -->
<!-- ELEMENT : defaultValue 參數值 -->
<!-- ====================================== -->
<!ELEMENT defaultValue (#PCDATA)>

<!--
[顯示樣式屬性說明]
// font 字型
// size 字體大小
// bold 粗體
// italic 斜體
// underline 底線
// color 文字顏色
// align 水平位置
// valign 垂直位置
// wrap 自動換行
// background 背景顏色
// borderSide 邊線位置
// borderStyle 邊線樣式
-->


<!--
[borderStyle 屬性說明]
NONE   無
THIN   薄
MEDIUM 中等的
DASHED 虛線
DOTTED 點綴
THICK 厚
DOUBLE 雙
HAIR 毛髮
MEDIUM_DASHED 中等虛線
DASH_DOT 點劃線
MEDIUM_DASH_DOT 中等點劃線
DASH_DOT_DOT 點點劃線
MEDIUM_DASH_DOT_DOT 中等點點劃線
SLANTED_DASH_DOT 斜沖點
-->

=== ilwu/RbtProject/srcAllen/com/rbt/export/test/AllenExport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "excel-operate-export.dtd">

<!-- =================================================================================== -->
<!-- ExcelOperate 套件 匯出功能的設定檔 -->
<!-- =================================================================================== -->
<config>

	<!-- =================================================================================== -->
	<!-- FUNCTION 設定區 -->
	<!-- =================================================================================== -->
	<!-- 產生序號 -->
	<function funcId="GEN_SEQ" className="com.rbt.util.exceloperate.function.ExcelOperateFunctionImpl" method="SEQ" />
	<!-- 產生民國年日期 -->
	<function funcId="CURR_ROC_DATE" className="com.rbt.util.exceloperate.function.ExcelOperateFunctionImpl" method="CURR_ROC_DATE" />

	<!-- =================================================================================== -->
	<!-- 匯出Excel格式 設定區 -->
	<!-- =================================================================================== -->

	<!-- ======================================================== -->
	<!-- 畢業生資料維護作業 -> 訓練生基本資料 -->
	<!-- ======================================================== -->
	<excel id="08-01-01-01" fileName="訓練生基本資料.xls">
		<style size="10" />
		<sheet sheetName="訓練生基本資料">
			<!-- ========================== -->
			<!-- title [context] 單筆欄位 -->
			<!-- ========================== -->
			<context dataId="title">
				<tr>
					<td defaultValue="「雙軌訓練旗艦計畫」訓練生基本資料" colspan="24" size="18" bold="true" />
				</tr>
				<tr>
					<td colspan="22" />
					<td defaultValue="製表日期：" align="right" size="10" bold="true" />
					<td funcId="CURR_ROC_DATE" size="10" bold="true" />
				</tr>
			</context>
			<!-- ========================== -->
			<!-- 表頭 [context] 單筆欄位 -->
			<!-- ========================== -->
			<context dataId="header">
				<tr background="GRAY_25" size="12">
					<td defaultValue="編號" width="8" />
					<td defaultValue="入學年度" width="6" />
					<td defaultValue="學制" width="6" />
					<td defaultValue="姓名" width="10" />
					<td defaultValue="學校名稱" width="35" />
					<td defaultValue="事業單位名稱" width="40" />
					<td defaultValue="職類" width="24" />
					<td defaultValue="班別" width="20" />
					<td defaultValue="學號" width="12" />
					<td defaultValue="身分證字號" width="14" />
					<td defaultValue="出生日期" width="12" />
					<td defaultValue="性別" width="6" />
					<td defaultValue="聯絡電話" />
					<td defaultValue="行動電話" />
					<td defaultValue="聯絡人" width="10" />
					<td defaultValue="聯絡人電話" />
					<td defaultValue="聯絡人行動電話" width="18" />
					<td defaultValue="郵遞區號" width="10" />
					<td defaultValue="住址" width="50" />
					<td defaultValue="訓練生英文名" width="22" />
					<td defaultValue="電子郵件" width="34" />
					<td defaultValue="就業動向代碼" width="8" />
					<td defaultValue="就業動向" />
					<td defaultValue="詳細情形" width="34" />
				</tr>
			</context>
			<!-- ========================== -->
			<!-- detail [detail] 多筆欄位 -->
			<!-- ========================== -->
			<detail dataId="detail">
				<column funcId="GEN_SEQ" /><!-- 編號 -->
				<column key="YEAR" /><!-- 入學年度 -->
				<column key="ES_NAME_CHN" /><!-- 學制 -->
				<column key="NAME" /><!-- 姓名 -->
				<column key="SCHOOL_CHN_NAME" align="left" /><!-- 學校名稱 -->
				<column key="CORP_CHN_NAME" align="left" /><!-- 事業單位名稱 -->
				<column key="ST_CHN_NAME" align="left" /><!-- 職類 -->
				<column key="CLASS_NAME" align="left" /><!-- 班別 -->
				<column key="STUDY_ID" /><!-- 學號 -->
				<column key="IDCARD_NUM" /><!-- 身分證字號 -->
				<column key="BIRTHDAY" /><!-- 出生日期 -->
				<column key="SEX_NAME" /><!-- 性別 -->
				<column key="HOME_PHONE" align="left" /><!-- 聯絡電話 -->
				<column key="MOBILE_PHONE" align="left" /><!-- 行動電話 -->
				<column key="LM_NAME" /><!-- 聯絡人 -->
				<column key="LM_PHONE" align="left" /><!-- 聯絡人電話 -->
				<column key="LM_MOBILE_PHONE" align="left" /><!-- 聯絡人行動電話 -->
				<column key="POST_ID" /><!-- 郵遞區號 -->
				<column key="ADDRESS" align="left" /><!-- 住址 -->
				<column key="ENG_NAME" align="left" /><!-- 訓練生英文名 -->
				<column key="EMAIL" align="left" /><!-- 電子郵件 -->
				<column key="WORK_CODE" /><!-- 就業動向代碼 -->
				<column key="WORK_CODE_NAME" align="left" /><!-- 就業動向 -->
				<column key="DETAIL" align="left" /><!-- 詳細情形 -->
			</detail>
		</sheet>
	</excel>

	<!-- ======================================================== -->
	<!-- 畢業生資料維護作業 ->各校就業率 -->
	<!-- ======================================================== -->
	<excel id="08-01-01-02" fileName="各校就業率.xls">
		<style width="10" />
		<sheet sheetName="各校就業率">
			<!-- ========================== -->
			<!-- title [context] 單筆欄位 -->
			<!-- ========================== -->
			<context dataId="title">
				<tr>
					<td defaultValue="「雙軌訓練旗艦計畫」畢業生就業調查表" colspan="18" size="18" bold="true" />
				</tr>
				<tr>
					<td colspan="16" />
					<td defaultValue="製表日期：" align="right" size="10" bold="true" />
					<td funcId="CURR_ROC_DATE" align="left" size="10" bold="true" />
				</tr>
			</context>
			<!-- ========================== -->
			<!-- header [context] 單筆欄位 -->
			<!-- ========================== -->
			<context dataId="header">
				<tr background="GRAY_25">
					<td defaultValue="編號" rowspan="2" width="8" />
					<td defaultValue="學校" rowspan="2" width="36" />
					<td defaultValue="入學年度" rowspan="2" />
					<td defaultValue="1.留任" rowspan="2" />
					<td defaultValue="2.就業" rowspan="2" />
					<td defaultValue="3.升學" colspan="5" />
					<td defaultValue="4.服役" rowspan="2" />
					<td defaultValue="5.創業" rowspan="2" />
					<td defaultValue="6.待業" rowspan="2" />
					<td defaultValue="7.其他" colspan="3" />
					<td defaultValue="8.總數" rowspan="2" />
					<td defaultValue="就業率" rowspan="2" width="24" />
				</tr>
				<tr background="GRAY_25">
					<td defaultValue="一般學制(要打工)" />
					<td defaultValue="一般學制(不要打工)" />
					<td defaultValue="繼續就讀本計畫" />
					<td defaultValue="其他建教合作" />
					<td defaultValue="出國讀書" />
					<td defaultValue="生病休養" />
					<td defaultValue="國家考試" />
					<td defaultValue="不確定" />
				</tr>
			</context>
			<!-- ========================== -->
			<!-- detail [detail] 多筆欄位 -->
			<!-- ========================== -->
			<detail dataId="detail">
				<column key="SEQ" funcId="GEN_SEQ" />
				<column key="SCHOOL_CHN_NAME" />
				<column>
					<!-- ========================== -->
					<!-- [column.array] 多筆欄位 -->
					<!-- ========================== -->
					<array dataId="yearDataList">
						<column key="YEAR" />
						<column key="1" defaultValue="0" />
						<column key="2" defaultValue="0" />
						<column key="3-1" defaultValue="0" />
						<column key="3-2" defaultValue="0" />
						<column key="3-3" defaultValue="0" />
						<column key="3-4" defaultValue="0" />
						<column key="3-5" defaultValue="0" />
						<column key="4" defaultValue="0" />
						<column key="5" defaultValue="0" />
						<column key="6" defaultValue="0" />
						<column key="7-1" defaultValue="0" />
						<column key="7-2" defaultValue="0" />
						<column key="7-3" defaultValue="0" />
						<column key="8" defaultValue="0" />
						<column key="EMPLOYMENT_RATE" />
					</array>
					<!-- ========================== -->
					<!-- [column.single] 單筆欄位 -->
					<!-- ========================== -->
					<single dataId="countMap">
						<column defaultValue="小計" background="BRIGHT_GREEN" />
						<column key="1" defaultValue="0" background="VERY_LIGHT_YELLOW" />
						<column key="2" defaultValue="0" background="VERY_LIGHT_YELLOW" />
						<column key="3" defaultValue="0" colspan="5" background="VERY_LIGHT_YELLOW" />
						<column key="4" defaultValue="0" background="VERY_LIGHT_YELLOW" />
						<column key="5" defaultValue="0" background="VERY_LIGHT_YELLOW" />
						<column key="6" defaultValue="0" background="VERY_LIGHT_YELLOW" />
						<column key="7" defaultValue="0" colspan="3" background="VERY_LIGHT_YELLOW" />
						<column key="8" defaultValue="0" background="VERY_LIGHT_YELLOW" />
						<column key="EMPLOYMENT_RATE" background="VERY_LIGHT_YELLOW" />
					</single>
				</column>
			</detail>
			<!-- ========================== -->
			<!-- footer [context] 單筆欄位 -->
			<!-- ========================== -->
			<context dataId="allTotalCount">
				<tr>
					<td defaultValue="合計" colspan="3" />
					<td key="1" defaultValue="0" />
					<td key="2" defaultValue="0" />
					<td key="3" defaultValue="0" colspan="5" />
					<td key="4" defaultValue="0" />
					<td key="5" defaultValue="0" />
					<td key="6" defaultValue="0" />
					<td key="7" defaultValue="0" colspan="3" />
					<td key="8" defaultValue="0" />
					<td key="EMPLOYMENT_RATE" />
				</tr>
			</context>
			<!-- ========================== -->
			<!-- note [context] 單筆欄位 -->
			<!-- ========================== -->
			<context dataId="note">
				<tr>
					<td colspan="18" bold="true" align="left" defaultValue="就業率計算：(1+2+5)%(8-3-4)" />
				</tr>
			</context>
		</sheet>
	</excel>

	<!-- ======================================================== -->
	<!-- 畢業生資料維護作業 -> 各入學年度就業率 -->
	<!-- ======================================================== -->
	<excel id="08-01-01-03" fileName="各入學年度就業率.xls">
		<style width="10" />
		<sheet sheetName="各入學年度就業率">
			<!-- ========================== -->
			<!-- title [context] 單筆欄位 -->
			<!-- ========================== -->
			<context dataId="title">
				<tr>
					<td defaultValue="「雙軌訓練旗艦計畫」畢業生就業調查" colspan="16" size="18" bold="true" />
				</tr>
				<tr>
					<td colspan="14" />
					<td defaultValue="製表日期：" borderStyle="NONE" borderSide="RIGHT" align="right" size="10" bold="true" />
					<td funcId="CURR_ROC_DATE" align="left" size="10" bold="true" />
				</tr>
			</context>
			<!-- ========================== -->
			<!-- header [context] 單筆欄位 -->
