=== ilwu/RbtProject/srcAllen/excel-operate-import.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- ====================================== -->
<!-- ELEMENT : config-->
<!-- ====================================== -->
<!ELEMENT config (function*|format|excel+)*>

<!-- ====================================== -->
<!-- ELEMENT : function -->
<!-- ====================================== -->
<!ELEMENT function EMPTY>
<!ATTLIST function
	funcId ID #REQUIRED
	className CDATA #REQUIRED
	method CDATA #REQUIRED
>

<!-- ====================================== -->
<!-- ELEMENT : format -->
<!-- ====================================== -->
<!ELEMENT format EMPTY>
<!ATTLIST format
	formatId ID #REQUIRED
	regex CDATA #REQUIRED
>

<!-- ====================================== -->
<!-- ELEMENT : excel-->
<!-- ====================================== -->
<!ELEMENT excel (read|params?)*>
<!ATTLIST excel
	id CDATA #REQUIRED
	sheetNum CDATA #REQUIRED
	startRow CDATA #REQUIRED
	checkEmptyRow (true|false) #IMPLIED
	checkDuplicate CDATA #IMPLIED
	desc CDATA #IMPLIED
>

<!-- ====================================== -->
<!-- ELEMENT : read -->
<!-- ====================================== -->
<!ELEMENT read (column+)>

<!-- ====================================== -->
<!-- ELEMENT : column -->
<!-- ====================================== -->
<!ELEMENT column (defaultValue?|funcParam?)>
<!ATTLIST column
	key CDATA #REQUIRED
	defaultValue CDATA #IMPLIED
	desc CDATA #IMPLIED
	funcId CDATA #IMPLIED
	funcParam CDATA #IMPLIED
	formatId CDATA #IMPLIED
	regex CDATA #IMPLIED
	checkNull CDATA #IMPLIED
	pass (true|false) #IMPLIED
	index CDATA #IMPLIED
>

<!-- ====================================== -->
<!-- ELEMENT : params -->
<!-- ====================================== -->
<!ELEMENT params (param+)>

<!-- ====================================== -->
<!-- ELEMENT : param -->
<!-- ====================================== -->
<!ELEMENT param (defaultValue?|funcParam?)>
<!ATTLIST param
	key CDATA #REQUIRED
	defaultValue CDATA #IMPLIED
	funcId CDATA #IMPLIED
	funcParam CDATA #IMPLIED
	desc CDATA #IMPLIED
	index CDATA #IMPLIED
>

<!-- ====================================== -->
<!-- ELEMENT : defaultValue 參數值 -->
<!-- ====================================== -->
<!ELEMENT defaultValue (#PCDATA)>

<!-- ====================================== -->
<!-- ELEMENT : funcParam 參數值 -->
<!-- ====================================== -->
<!ELEMENT funcParam (#PCDATA)>


<!--

( ) 一個表示式
A A 必須出現一次(出現1次)
A? A 可出現一次或不出現(出現0 or 1次)
A+ A 可重複出現且至少出現一次(出現1次以上)
A* A 可重複出現或不出現(出現0次以上)
(A | B | C) A, B, C 任選一出現，且僅能有一出現
(A, B, C) A, B, C 同時出現，且出現順序為A, B, C
(A | B | C)+ …
(A?, B*, C+) …

-->

=== ilwu/RbtProject/srcExcelOpt/import_sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config SYSTEM "excel-operate-import.dtd">

<!-- =================================================================================== -->
<!-- ExcelOperate 套件 匯入功能的設定檔 -->
<!-- =================================================================================== -->
<config>

	<!-- =================================================================================== -->
	<!-- FUNCTION 設定區 -->
	<!-- =================================================================================== -->
	<!-- 產生序號 -->
	<function funcId="GEN_SEQ" className="com.rbt.util.exceloperate.function.ExcelOperateFunctionImpl" method="SEQ" />
	<!-- 產生民國年日期 -->
	<function funcId="CURR_ROC_DATE" className="com.rbt.util.exceloperate.function.ExcelOperateFunctionImpl" method="CURR_ROC_DATE" />


	<!-- =================================================================================== -->
	<!-- 正規表示式檢核設定區 -->
	<!-- =================================================================================== -->
	<!-- 身份證字號 -->
	<format formatId="ID_NUM" regex="^[A-Z]{1}[1-2]{1}[0-9]{8}$" />
	<!-- 生日 -->
	<format formatId="BIRTHDAY" regex="^[A-Z]{1}[1-2]{1}[0-9]{8}$" />
	<!-- 統編 -->
	<format formatId="BUSINESS_REGISTRATION_CODE" regex="^[A-Z]{1}[1-2]{1}[0-9]{8}$" />
	<!-- 日期 -->
	<format formatId="FORMAT_DATE" regex="^(19|20)[0-9]{2}[\/\-\.](0[1-9]|1[012])[\/\-\.](0[1-9]|[12][0-9]|3[01])$" />

	<!-- =================================================================================== -->
	<!-- 匯入Excel格式 設定區 -->
	<!-- =================================================================================== -->

	<!-- ====================================================================== -->
	<!-- 畢業生 > 勞保資料匯入 -->
	<!-- ====================================================================== -->
	<excel id="LaborInsurance" desc="畢業生勞保資料匯入" sheetNum="1" startRow="2" checkEmptyRow="false" checkDuplicate="IDCARD_NUM,COMPANY_ID,SECURE_SATUS,CHANGE_DATE" >
		<read>
			<column desc="身分證字號" key="IDCARD_NUM" checkNull="false" formatId="ID_NUM" />
			<column desc="姓名" key="CHN_NAME" checkNull="false" regex="^.{0,10}$" />
			<column desc="生日" key="BRITHDAY" checkNull="false" formatId="BIRTHDAY" />
			<column desc="統一編號" key="COMPANY_ID" checkNull="false" formatId="BUSINESS_REGISTRATION_CODE" />
			<column desc="保險證號" key="SECURE_ID" checkNull="false" regex="^.{0,120}$" />
			<column desc="投保機構名稱" key="COMPANY_NAME" checkNull="true" regex="^.{0,150}$" />
			<column desc="加退保" key="SECURE_SATUS" checkNull="true" />
			<column desc="投保薪資" key="SECURE_PAY" checkNull="true" regex="[0-9]*([.][0-9]*)?" />
			<column desc="異動日期" key="CHANGE_DATE" checkNull="false" formatId="FORMAT_DATE">
				<defaultValue>0000-00-00</defaultValue>
			</column>
		</read>
	</excel>
</config>
